name: veritrust_example
description: VeriTrust AI SDK Demo — YONO 2.0 Integration Showcase
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter
  veritrust_sdk:
    path: ../
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
